# Generated by Django 5.0.2 on 2024-02-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_rename_recipe_rating_rated_recipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="voted",
        ),
    ]
