# Generated by Django 5.0.2 on 2024-02-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="rating",
            new_name="rating_total",
        ),
    ]
