# Generated by Django 5.0.2 on 2024-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_remove_recipe_ingredients_recipe_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients_list",
            field=models.TextField(default="", max_length=255),
        ),
    ]
