# Generated by Django 5.0.2 on 2024-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_ingredients_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="price_total",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients_list",
            field=models.JSONField(default=dict),
        ),
    ]
