# Generated by Django 5.0.2 on 2024-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_recipe_price_total_alter_recipe_ingredients_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingridients_price_list",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="price_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
